version: "2.3"

services:
  noetic-nhoa_bt-simple:
    network_mode: host
    container_name: "noetic-nhoa_bt-simple"
    image: gitlab.local.eurecat.org:5050/robotics-automation/nhoa:noetic-nhoa_bt-simple
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/docker/.xauth_docker/share:/tmp/xauth # Option A.
      # - ~/${WORK_SPACE}/.xauth_docker/share:/tmp/xauth # Option B. TODO: Modify "${WORK_SPACE}" for your local path
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth   
    devices:
      - /dev/dri:/dev/dri
  
  melodic-ari:
    network_mode: host
    container_name: "melodic-ari"
    image: gitlab.local.eurecat.org:5050/robotics-automation/nhoa:melodic-ari
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/docker/.xauth_docker/share:/tmp/xauth # Option A.
      # - ~/${WORK_SPACE}/.xauth_docker/share:/tmp/xauth # Option B. TODO: Modify "${WORK_SPACE}" for your local path
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth   
    devices:
      - /dev/dri:/dev/dri