version: "2.3"

services:
  noetic-nhoa_bt:
    network_mode: host
    container_name: "noetic-nhoa_bt"
    image: ghcr.io/nhoa-project/noetic-nhoa_bt:latest # GitHub Option.
    # image: gitlab.local.eurecat.org:5050/robotics-automation/nhoa:noetic-nhoa_bt # Gitlab Option. (ONLY EUT)
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/docker/.xauth_docker/share:/tmp/xauth # Option A.
      # - ~/${WORK_SPACE}/.xauth_docker/share:/tmp/xauth # Option B. TODO: Modify "${WORK_SPACE}" for your local path
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth   
    devices:
      - /dev/dri:/dev/dri
  
  melodic-ari:
    network_mode: host
    container_name: "melodic-ari"
    image: registry.gitlab.com/pal-robotics/nhoa/dockers/pal-ferrum-pal-metapkg-development-ari-20-dev
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/docker/.xauth_docker/share:/tmp/xauth # Option A.
      # - ~/${WORK_SPACE}/.xauth_docker/share:/tmp/xauth # Option B. TODO: Modify "${WORK_SPACE}" for your local path
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/xauth/.docker.xauth   
    devices:
      - /dev/dri:/dev/dri